theme: just-the-docs

title: Restrainite
description: A ResoniteModLoader mod for Resonite that allows others to control restrictions of the local user.

aux_links:
  "Download":
    - "https://github.com/Restrainite/Restrainite/releases/latest"
  "Restrainite on GitHub":
    - "https://github.com/Restrainite/Restrainite"

color_scheme: dark


callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: purple
