remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Restrainite
description: A ResoniteModLoader mod for Resonite that allows others to control restrictions of the local user.

show_downloads: true
github:
  repository_url: https://github.com/Restrainite/RestrainiteMod
