theme: just-the-docs

title: Restrainite
description: A ResoniteModLoader mod for Resonite that allows others to control restrictions of the local user.

aux_links:
  "Download":
    - "https://github.com/Restrainite/RestrainiteMod/releases/latest"
  "RestrainiteMod on GitHub":
    - "https://github.com/Restrainite/RestrainiteMod"

color_scheme: dark


callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: purple
